<!-- 
Exceptional Handling : Exception is an error that occured during the code execution and it can handle by try, catch and finally blocks to catch the error 
-->
<script>
    console.log('Task 1')
    function setTime() {
        console.log(z);
    }
    try {
        setTime()
    } 
    catch {
        console.log('Some Error Occured in someTask function and Handled')
    }
    console.log('Task 2')
    console.log('Task 3')

    RefreneceError
    console.log('Task 1')
    try {
        console.log(z)
    } catch {
        console.log('Exception handled')
    }
    console.log('Task 3')

    // Run Time Error
    let a = 10
    let b = 0
    try {
        let result = a / b;
        console.log(result)
    } catch (error){
        console.log('An error occured:', error.message);
    }
</script>